### ISSUE TITLE
An issue with async/timeout

### ISSUE THREAD

**Issue by vovata** [mhjort/clj-gatling#53] opened 2017-10-25 13:57 UTC
There is raised an issue when the concurrency is high, and the concurrency distribution left much enough users to wait 200 milisecond to check again is it should run now. As the implementation of async/timeout uses timeouts map there is a case when one timeout channel instance is used for async take multiple times. Then an error is raised:
xception in thread "async-dispatch-216" java.lang.AssertionError: Assert failed: No more than 1024 pending takes are allowed on a single channel.
(< (.size takes) impl/MAX-QUEUE-SIZE)
	at clojure.core.async.impl.channels.ManyToManyChannel.take_BANG_(channels.clj:235)
	at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:983)
	at clojure.core.async.impl.ioc_macros$take_BANG_.invoke(ioc_macros.clj:982)
	at clj_gatling.simulation$run_scenario_constantly$fn__818$state_machine__5041__auto____847$fn__849.invoke(simulation.clj:116)
	at clj_gatling.simulation$run_scenario_constantly$fn__818$state_machine__5041__auto____847.invoke(simulation.clj:109)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5059.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__735.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

My test scenario is executed with concurrency 10k and concurrency-distribution 0.1. When I remove the distribution the problem with the timeout disappeared because no one user has to wait.

**Comment by mhjort** [comment] 2017-10-25 17:53
Seems there is a bug. However, I was unable to reproduce this one. Could you provide an code example that I could use to investigate more?

**Comment by vovata** [comment] 2017-10-26 07:39
It is something close to my implementation.

(ns tests.timeout-issue
  (:require [clj-gatling.core :as gat]
            [taoensso.timbre :as timbre]
            [clojure.core.async :as a]
            [mount.core :as mount]))

(defn- setup
  "Initializing test context"
  [context]
  (timbre/info "Calling setup ...")
  (mount/start)
  (timbre/info "context: " context)
  context)

(defn- step-1 [context]
  (a/go
    (a/<! (a/timeout 200))))

(def step-2 step-1)
(def step-3 step-1)
(def step-4 step-1)
(def step-5 step-1)
(def step-6 step-1)
(def step-7 step-1)
(def step-8 step-1)

(defn- cleanup
  "Cleanup of test related data."
  [context]
  (timbre/info "Calling cleanup ...")
  (mount/stop)
  (timbre/info "Context cleaned up."))

(defn run-load [concurrency]
  (let [context {}]
    (gat/run {:name      "Simulation"
              :pre-hook  setup
              :post-hook cleanup
              :scenarios [{:name                     "Scenario"
                           :skip-next-after-failure? true   ;Optional (default true)
                           :allow-early-termination? true   ;Optional (default false)
                           :steps                    [{:name    "Step One"
                                                       :request step-1}
                                                      {:name    "Step Two"
                                                       :request step-2}
                                                      {:name    "Step Three"
                                                       :request step-3}
                                                      {:name    "Step Four"
                                                       :request step-4}
                                                      {:name    "Step Five"
                                                       :request step-5}
                                                      {:name    "Step Six"
                                                       :request step-6}
                                                      {:name    "Step Seven"
                                                       :request step-7}
                                                      {:name    "Step Eight"
                                                       :request step-8}
                                                      ]}]}
             {:concurrency              concurrency
              :concurrency-distribution (constantly 0.01)
              :timeout-in-ms            10000
              :context                  context}))
  )

(comment (run-load 10000))

And the error is the same as in my implementation:
Exception in thread "async-dispatch-2218" java.lang.AssertionError: Assert failed: No more than 1024 pending takes are allowed on a single channel.
(< (.size takes) impl/MAX-QUEUE-SIZE)
	at clojure.core.async.impl.channels.ManyToManyChannel.take_BANG_(channels.clj:235)
	at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:983)
	at clojure.core.async.impl.ioc_macros$take_BANG_.invoke(ioc_macros.clj:982)
	at clj_gatling.simulation$run_scenario_constantly$fn__818$state_machine__5041__auto____847$fn__849.invoke(simulation.clj:116)
	at clj_gatling.simulation$run_scenario_constantly$fn__818$state_machine__5041__auto____847.invoke(simulation.clj:109)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5059.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__735.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mhjort** [comment] 2017-10-30 17:06
I tried to reproduce the bug with the code sent. For me it works with and without concurrency-distribution function. One thing I noticed in your scenario. There should be no point on using concurrency distribution function which is returning constantly a same value. The concurrency distribution should be used only in those cases where you want to ramp up or down the concurrency.

**Comment by vovata** [comment] 2017-10-31 09:13
It is strange that you can't reproduce the issue.
I always reproduce it, each run is the same.
What is your running environment? I'm using Fedora 26, with Oracle JDK 1.8.0_141, clojure 1.8 and higher, lein 2.7.0

**Comment by mhjort** [comment] 2017-11-06 18:47
Yep. Strange. My running environment is latest Linux Mint, with Oracle JDK java version "1.8.0_151", Clojure 1.8 and Lein 2.7.1.

I also released new version of clj-gatling `0.11.0` where I have updated  core.async to latest version. Could you try with that one?

**Comment by vovata** [comment] 2017-11-08 10:59
It is better, but not perfect.
Sometimes it passes, but somethimes it continues to fail with this error.
I think the problem is not in your implementation, but in the implementation of async/timeout, where a cache of channels for timeouts is used. When much more same timeout channels are requested, then one channel from the cache is used for more than 1024 takes. To avoid this issaue in async implementation, it has to avoid such massive use of it in clj-gatling. When the concurrency-distributoin is activated, then all waiting scenarious use same async/timeout 200 channel, and when the waiting scenarious are much enough (about 10k) it is easy to rich more than 1024 takes on same cached timeot channel. For larger waiting scenarious it will be easier to rich this limit of 1024 takes per channel. Could you find a solution to avoid these many async/timeout takes when waiting for scenarious starting? May be less takes ... or just one timeout take for all waiting scenarious ...

**Comment by mhjort** [comment] 2018-11-21 18:15
There is now a beta version where this should be fixed if someone wants to test `0.14.0-beta1`. It is based on solution in https://github.com/mhjort/clj-gatling/pull/60

**Closed** 2020-06-17 14:36 UTC
